

#Using SID
#spring.jta.atomikos.datasource.xa-data-source-class-name=oracle.jdbc.xa.client.OracleXADataSource
#spring.jta.atomikos.datasource.xa-properties.url=jdbc:oracle:thin:@10.0.1.194:1521/XE



spring.datasource.url=jdbc:oracle:thin:@//sbruat.cfwyptiydnao.ap-south-1.rds.amazonaws.com:9878/sbruat
spring.datasource.username=sbrdbadmin
spring.datasource.password=SbrDe5dMin1

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


#spring.datasource.url=jdbc:oracle:thin:@10.0.1.194:1521/XE

#hibernate configs
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#spring.mail.properties.mail.smtp.socketFactory.port=587
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=dipssonawane123@gmail.com
#spring.mail.password=gewa fsgo noit oini 
#spring.mail.properties.mail.smtp.auths=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher

com.mahasbr.jwtSecret= rkv2Xu9hfEaxGlnsc1dxvukP4zyYOlQFbHsA+z6dvqD38B9WgccqqZah9MitgkrK1/ASXPTGpVrZZ7EkUr2x0w==
com.mahasbr.jwtExpirationMs=86400000

#location for file upload
app.upload.base-dir=${FILE_UPLOAD_DIR:/data/upload}
app.file.upload-dir=${FILE_UPLOAD_DIR:/data/upload}
file.upload-dir=${FILE_UPLOAD_DIR:/data/upload}
mahasbrcircularfileupload.locationLinux=${FILE_UPLOAD_DIR:/data/upload}
app.file.circular-max-file-size-mb=${CIRCULAR_MAX_FILE_SIZE_MB:25}
app.file.virus-scan-required=${VIRUS_SCAN_REQUIRED:true}
