package com.mahasbr.dto;

public record RegisteredEstablishmentExportDto(
		Long srNo,
		String establishmentName,
		String houseNo,
		String streetName,
		String locality,
		String pinCode,
		String telephoneNumber,
		String emailAddress,
		String panNumber,
		String tanNumber,
		String headOfficeHouseNo,
		String headOfficeStreetName,
		String headOfficeLocality,
		String headOfficePinCode,
		String headOfficeTelephoneNumber,
		String headOfficeEmailAddress,
		String headOfficePanNumber,
		String headOfficeTanNumber,
		String majorActivityDescription,
		String nic2008ActivityCode,
		String nic2008ActivityCodeDescription,
		String yearOfStartOfOperation,
		String ownershipCode,
		String totalPersonsWorking,
		String actAuthorityRegistrationNumbers,
		String remarks,
		String locationCode,
		String registrationStatus,
		String brn,
		String townVillage,
		String taluka,
		String district,
		String sector,
		String wardNumber,
		String authorityName,
		String actName,
		String registrationDate,
		String deregistrationExpiryDate,
		String gstNumber,
		String hsnCode) {
}
